### ISSUE TITLE
Develop guides to each topic

### ISSUE THREAD

**Issue by AnnaSyme** [melbournebioinformatics/MelBioInf_docs#40]
Guides to cover:
- brief overview (e.g. RNA-seq for DGE)
- relevant tutorials
- relevant web links to articles, other training

**Comment by claresloggett** [comment]
I've started a doc to write down guides we think we should create, here: https://docs.google.com/document/d/1R71OxMb0dgjAYrfbvv0pdHDd2eIUzDxml7rqTgaDft0/edit

Should we also link to your format template Anna?

**Comment by AnnaSyme** [comment]
Guides are being drafted in the MelBioinf_docs_test repo.

**Comment by AnnaSyme** [comment]
Danny suggests adding in Pip's FAIR data information. Will ask Pip when she gets back.

**Comment by vinisalazar** [comment]
Closing this as stale. Please re-open if necessary.
