### ISSUE TITLE
Fix Question-Hint-Answer formatting in Proteomics

### ISSUE THREAD

**Issue by AnnaSyme** [melbournebioinformatics/MelBioInf_docs#61]
use: 

<details>
<summary>Hint</summary>
text
</details>

<details>
<summary>Answer</summary>
text
</details>

This is not as nice as mdx.showable but that isn't working.

**Comment by vinisalazar** [comment]
Closing this as we are using collapse Material for MkDocs [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) for this. Example [see Git workshop.](https://www.melbournebioinformatics.org.au/tutorials/tutorials/git/git/#undoing-changes)

@AnnaSyme please feel free to re-open if necessary.

**Comment by vinisalazar** [comment]
@egmg726 is it okay for me to close the other stale issues?

**Comment by egmg726** [comment]
@vinisalazar Yup, go for it!
