### ISSUE TITLE
HPC and Unix tutorials - update if required

### ISSUE THREAD

**Issue by AnnaSyme** [melbournebioinformatics/MelBioInf_docs#65]
I have added links to the most recent version of these, which is at Andrew Robinson's page (http://andrewjrobinson.github.io/vlsci-docs/tutorials/unix/). Our version is older. 

pros: better formatting for mdx.showable; cons: LaTrobe icon is included

Our formatting for question-hint-answer does not render as nicely as mdx.showable. 

Ideally we will update our version at some stage, or remove in favour of pointing to alternate courses (e.g. run by Research Platforms).

**Comment by claresloggett** [comment]
@supernifty updated our tutorials last year, so they're now more up to date than the La Trobe version.

We also have a link to Lev's resources at Research Platforms (https://github.com/UoM-ResPlat-DevOps/SpartanBioinformatics) which we will put up as he's just run a tailored workshop for our users.
