### ISSUE TITLE
Can't download datasets in Galaxy

### ISSUE THREAD

**Issue by Weronika77** [melbournebioinformatics/MelBioInf_docs#71]
Hi,

I'm trying[ this](https://www.melbournebioinformatics.org.au/tutorials/tutorials/proteomics_basic/background_protein_prophet/) tutorial in proteomics, but I can't view the data since it gives me this error in Galaxy:
```
Bad Request 

The server could not comply with the request since it is either malformed or otherwise incorrect.
```

**Comment by iracooke** [comment]
Thanks for this issue report.  The urls needed to be updated.  Wherever you have a URL that starts like this

https://swift.rc.nectar.org.au:8888/v2/

Please change it to this

https://swift.rc.nectar.org.au:8888/v1/

**Comment by claresloggett** [comment]
Thanks @iracooke . Do we know why v1 works and v2 doesn't (and if that will be the ongoing situation)?
